# Generated by Django 5.0.1 on 2024-11-15 21:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_student_device_number'),
        ('teacher', '0002_academic_tasks_date_academic_tasks_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('is_present', models.BooleanField(default=True, verbose_name='حاضر')),
                ('reason_absence', models.TextField(blank=True, null=True)),
                ('permission_type', models.CharField(choices=[('none', 'بدون إذن'), ('half_day', 'نصف يوم'), ('excused', 'إجازة بعذر'), ('medical', 'إجازة طبية'), ('emergency', 'حالة طارئة'), ('other', 'سبب آخر')], default='none', max_length=50, verbose_name='نوع الإذن')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب الغياب/الإذن')),
                ('permission_start_time', models.TimeField(blank=True, null=True, verbose_name='وقت بدء الإذن')),
                ('permission_end_time', models.TimeField(blank=True, null=True, verbose_name='وقت انتهاء الإذن')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.schoolclass', verbose_name='الفصل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student', verbose_name='الطالب')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name_plural': 'خروج نصف يوم',
            },
        ),
    ]
