# Generated by Django 5.0.1 on 2024-11-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_student_device_number'),
        ('teacher', '0003_student_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_Attendance',
            new_name='leve_student',
        ),
    ]
