# Generated by Django 5.0.1 on 2024-11-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_rename_student_attendance_leve_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leve_student',
            name='reason_absence',
        ),
    ]
