# Generated by Django 5.0.1 on 2024-11-15 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_student_device_number'),
        ('teacher', '0006_alter_leve_student_permission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leve_student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.schoolclass', verbose_name='الفصل'),
        ),
    ]
