# Generated by Django 5.0.1 on 2024-09-01 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_schoolclass_students'),
        ('manger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_to_parent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='info_to_Parent/', verbose_name='  -'),
        ),
        migrations.AlterField(
            model_name='info_to_parent',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student', verbose_name='Parent'),
        ),
    ]
