# Generated by Django 5.0.1 on 2024-09-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manger', '0003_alter_info_to_parent_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info_to_parent',
            old_name='Parent',
            new_name='student',
        ),
    ]
