# Generated by Django 5.0.1 on 2024-10-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_student_gender_student_mother_name_and_more'),
        ('manger', '0005_teacherattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_to_Parent_by_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='info_to_Parent/')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student', verbose_name='Parent')),
            ],
        ),
        migrations.CreateModel(
            name='InfoToAllStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='مهمة أو رسالة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='info_to_all_students/', verbose_name='صورة')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.schoolclass', verbose_name='الفصل')),
            ],
            options={
                'verbose_name_plural': 'رسائل لجميع الطلاب في الفصل',
            },
        ),
    ]
