# Generated by Django 5.0.1 on 2024-10-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manger', '0006_info_to_parent_by_class_infotoallstudents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoToAllStudents',
        ),
    ]
