# Generated by Django 5.0.1 on 2024-10-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_student_gender_student_mother_name_and_more'),
        ('manger', '0007_delete_infotoallstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_to_parent_by_class',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student', verbose_name='Student'),
        ),
    ]
