# Generated by Django 5.0.1 on 2024-10-04 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manger', '0008_alter_info_to_parent_by_class_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_to_parent_by_class',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
