# Generated by Django 5.0.1 on 2024-10-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manger', '0009_info_to_parent_by_class_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_to_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('event_info', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='info_to_Parent/')),
            ],
        ),
    ]
