# Generated by Django 4.2.4 on 2024-08-08 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='SchoolClass_data',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_class_representative': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.schoolclass', verbose_name='  الفصل '),
        ),
        migrations.AddField(
            model_name='student',
            name='adres',
            field=models.TextField(default=1, verbose_name='  عنوان السكن  '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='father',
            field=models.CharField(default=1, max_length=150, verbose_name='اسم ولي الامر '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='father_nammber',
            field=models.CharField(default=1, max_length=150, verbose_name=' رقم ولي الامر '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='file_namber',
            field=models.CharField(default=1, max_length=150, verbose_name='رقم الملف '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='   ملحظات عامة   '),
        ),
    ]
