# Generated by Django 4.2.4 on 2024-08-08 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_schoolclass_data_student_adres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='SchoolClass_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.schoolclass', verbose_name='  الفصل '),
        ),
    ]
