# Generated by Django 5.0.1 on 2024-08-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_subject_teacher_classes_parent_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name_plural': ' الدرجات'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name_plural': 'ولي الامر'},
        ),
        migrations.AlterModelOptions(
            name='principal',
            options={'verbose_name_plural': 'المدير'},
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name_plural': ' الفصل'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': ' الطالب'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': ' المادةالدرسية'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': ' المدرس'},
        ),
    ]
