# Generated by Django 5.0.1 on 2024-08-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name_plural': 'الفصل'},
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='students',
            field=models.ManyToManyField(related_name='school_classes', to='home.student', verbose_name='الطلاب'),
        ),
    ]
