# Generated by Django 5.0.1 on 2024-08-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phon',
            field=models.CharField(default=1, max_length=150, verbose_name='رقم الهاتف '),
            preserve_default=False,
        ),
    ]
