# Generated by Django 5.0.1 on 2024-08-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_teacher_phon'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phon',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='رقم الهاتف '),
        ),
    ]
