# Generated by Django 5.0.1 on 2024-08-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_teacher_notes_alter_teacher_phon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='وصف المهمة'),
        ),
    ]
