# Generated by Django 5.0.1 on 2024-08-31 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='students',
        ),
    ]
