# Generated by Django 5.0.1 on 2024-09-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_schoolclass_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='is_present',
            new_name='absent',
        ),
    ]
