# Generated by Django 5.0.1 on 2024-09-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_is_present_attendance_absent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='absent',
            new_name='is_present',
        ),
    ]
