# Generated by Django 5.0.1 on 2024-10-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('feminine', 'feminine')], max_length=150, null=True, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default=1, max_length=150, verbose_name='اسم الام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mother_number',
            field=models.CharField(default=1, max_length=150, verbose_name='رقم الام'),
            preserve_default=False,
        ),
    ]
