# Generated by Django 5.0.1 on 2024-10-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_student_gender_student_mother_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت انتهاء الحصة'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت بدء الحصة'),
        ),
    ]
