# Generated by Django 5.0.1 on 2024-10-21 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_grade_options_grade_exam_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.schoolclass', verbose_name='الفصل'),
            preserve_default=False,
        ),
    ]
