# Generated by Django 5.0.1 on 2024-10-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_grade_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='school_class',
        ),
    ]
