# Generated by Django 5.0.1 on 2024-10-21 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_grade_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.schoolclass', verbose_name='الفصل'),
        ),
    ]
