# Generated by Django 5.0.1 on 2024-10-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_grade_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Approved',
            field=models.BooleanField(default=False, verbose_name='تمت المهمة'),
        ),
    ]
