# Generated by Django 5.0.1 on 2024-09-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
    ]
